#!/usr/bin/env bash
#
# colors
# Define colors and helpers to print message in color.
#
# Author: Armand Philippot <https://www.armandphilippot.com/>

set -e

###############################################################################
# Colors
###############################################################################
_COLOR_RESET=$(printf '\e[0m')
_COLOR_RED=$(printf '\e[31m')
_COLOR_GREEN=$(printf '\e[32m')
_COLOR_YELLOW=$(printf '\e[33m')
_COLOR_BLUE=$(printf '\e[34m')
_COLOR_MAGENTA=$(printf '\e[35m')

###############################################################################
# Helpers
###############################################################################

error() {
  printf "%sError:%s %s\n" "$_COLOR_RED" "$_COLOR_RESET" "$1"
}

highlight() {
  printf "%s%s%s\n" "$_COLOR_MAGENTA" "$1" "$_COLOR_RESET"
}

info() {
  printf "%sInfo: %s %s\n" "$_COLOR_BLUE" "$_COLOR_RESET" "$1"
}

option() {
  printf "%s%s%s\n" "$_COLOR_BLUE" "$1" "$_COLOR_RESET"
}

skipped() {
  printf "%sSkipped:%s %s\n" "$_COLOR_YELLOW" "$_COLOR_RESET" "$1"
}

success() {
  printf "%sSuccess:%s %s\n" "$_COLOR_GREEN" "$_COLOR_RESET" "$1"
}

warning() {
  printf "%sWarning:%s %s\n" "$_COLOR_YELLOW" "$_COLOR_RESET" "$1"
}

###############################################################################
# Export
###############################################################################
export _COLOR_RESET
export _COLOR_RED
export _COLOR_GREEN
export _COLOR_YELLOW
export _COLOR_BLUE
export _COLOR_MAGENTA
export -f error
export -f highlight
export -f info
export -f option
export -f skipped
export -f success
export -f warning
