#!/usr/bin/env bash
#
# config_zsh
# Create missing paths and move Zsh files to XDG directories.
# Depend on ./colors to print messages in colors. Make sure the file exists.
#
# Author: Armand Philippot <https://www.armandphilippot.com/>

set -e

configure_zsh() {
  info "Configuring Zsh..."

  local _zsh_cache_path="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
  local _zsh_config_path="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
  local _zsh_data_path="${XDG_DATA_HOME:-$HOME/.local/share}/zsh"

  if [ ! -d "$_zsh_cache_path" ]; then
    info "Creating $_zsh_cache_path..."
    mkdir -p "$_zsh_cache_path"
  fi

  if [ ! -d "$_zsh_config_path" ]; then
    info "Creating $_zsh_config_path..."
    mkdir -p "$_zsh_config_path"
  fi

  if [ ! -d "$_zsh_data_path" ]; then
    info "Creating $_zsh_data_path..."
    mkdir -p "$_zsh_data_path"
  fi

  if [ -e "$HOME/.zshrc" ]; then
    info "Moving $HOME/.zshrc..."
    mv "$HOME/.zshrc" "$_zsh_config_path/.zshrc"
  fi

  if [ -e "$HOME/.zlogin" ]; then
    info "Moving $HOME/.zlogin..."
    mv "$HOME/.zlogin" "$_zsh_config_path/.zlogin"
  fi

  if [ -e "$HOME/.zlogout" ]; then
    info "Moving $HOME/.zlogout..."
    mv "$HOME/.zlogout" "$_zsh_config_path/.zlogout"
  fi

  if [ -e "$HOME/.zprofile" ]; then
    info "Moving $HOME/.zprofile..."
    mv "$HOME/.zprofile" "$_zsh_config_path/.zprofile"
  fi

  if [ -e "$HOME/.zsh_history" ]; then
    info "Moving $HOME/.zsh_history..."
    mv "$HOME/.zprofile" "$_zsh_data_path/history"
  fi

  if [ -f "$HOME/.zshenv" ] && [ ! -h "$HOME/.zshenv" ]; then
    info "Moving $HOME/.zshenv..."
    mv "$HOME/.zshenv" "$_zsh_config_path/.zshenv"
    ln -s "$_zsh_config_path/.zshenv" "${HOME}/.zshenv"

    # These variables may have already been declared so it is not very clean.
    # But I will overwrite the files with my dotfiles so it is only temporary.
    printf "\nexport ZDOTDIR=%s\n" "$_zsh_config_path" >>"$_zsh_config_path"/.zshenv
    printf "\nexport HISTFILE=%s\n" "$_zsh_data_path/history" >>"$_zsh_config_path"/.zshenv
  fi

  success "Zsh configured!"
}

export -f configure_zsh
